import './styles.css';
import './fixes.css';
import { AudioEngine } from './audio/AudioEngine';
import { AppState } from './state/AppState';
import { PresetRegistry } from './presets/registry';
import { nebulaPreset } from './presets/nebula';
import { gravityPreset } from './presets/gravity';
import { bloomPreset } from './presets/bloom';
import { UniverseRenderer } from './rendering/UniverseRenderer';
import { FallbackRenderer } from './rendering/FallbackRenderer';
import { applyLanguage } from './i18n';
import type { AudioFrame } from './types';

const $ = <T extends HTMLElement>(selector: string): T => document.querySelector<T>(selector)!;
const state = new AppState(); const audio = new AudioEngine(); const registry = new PresetRegistry();
[nebulaPreset, gravityPreset, bloomPreset].forEach((preset) => registry.register(preset));
const canvas = $('#universe') as HTMLCanvasElement; const fallbackCanvas = $('#fallback') as HTMLCanvasElement;
let renderer: UniverseRenderer | undefined; let fallback: FallbackRenderer | undefined;
try { renderer = new UniverseRenderer(canvas, registry, state); renderer.setPreset(state.activePreset); renderer.start(); } catch { canvas.hidden = true; fallbackCanvas.hidden = false; fallback = new FallbackRenderer(fallbackCanvas); }

const player = $('#player'); const landing = $('#landing'); const fileInput = $('#audioFile') as HTMLInputElement;
const showMessage = (text: string) => { const node = $('#message'); node.textContent = text; node.classList.add('visible'); window.setTimeout(() => node.classList.remove('visible'), 3200); };
const enter = () => { document.body.classList.add('music-active'); landing.setAttribute('aria-hidden', 'true'); };
const format = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;

const worlds = $('#worlds');
registry.list().forEach((preset, index) => { const button = document.createElement('button'); button.type = 'button'; button.role = 'tab'; button.dataset.id = preset.id; button.innerHTML = `<span>0${index + 1}</span><strong>${preset.name}</strong>`; button.title = preset.description; button.addEventListener('click', () => renderer?.setPreset(preset.id)); worlds.append(button); });
state.subscribe(() => { document.body.classList.toggle('ui-hidden', state.uiHidden); document.querySelectorAll<HTMLButtonElement>('#worlds button').forEach((button) => { const active = button.dataset.id === state.activePreset; button.classList.toggle('active', active); button.setAttribute('aria-selected', String(active)); }); const preset = registry.get(state.activePreset); $('#worldDescription').textContent = preset.description; ($('#reducedButton') as HTMLButtonElement).setAttribute('aria-pressed', String(state.reducedMotion)); }); state.notify();

audio.onState(({ playing, name }) => { $('#trackName').textContent = name; $('#statusText').textContent = playing ? 'SIGNAL ACTIVE' : 'SIGNAL PAUSED'; $('#playButton').textContent = playing ? 'Ⅱ' : '▶'; document.body.classList.toggle('playing', playing); });
const load = async (file?: File) => { if (!file) return; try { await audio.loadFile(file); enter(); switchView('listen'); } catch (error) { showMessage((error as Error).message === 'FILE_TOO_LARGE' ? 'File exceeds the 100 MB limit / 文件超过 100 MB' : 'This audio could not be decoded / 无法解码此音频'); } };
fileInput.addEventListener('change', () => void load(fileInput.files?.[0]));
$('#demoButton').addEventListener('click', async () => { try { await audio.playDemo(); enter(); } catch { showMessage('Audio permission was denied / 音频权限被拒绝'); } });
$('#playButton').addEventListener('click', () => void audio.toggle());
const volumeInput = $('#volume') as HTMLInputElement;
volumeInput.addEventListener('input', () => { const value = Number(volumeInput.value); audio.setVolume(value); $('#volumeValue').textContent = String(Math.round(value * 100)); $('#levelOutput').textContent = `OUTPUT · ${Math.round(value * 100)}%`; });
($('#filter') as HTMLInputElement).addEventListener('input', (event) => { const value = Number((event.target as HTMLInputElement).value); audio.setFilter(value); $('#filterKnob').style.setProperty('--turn', `${-135 + value * 270}deg`); });
($('#sensitivity') as HTMLInputElement).addEventListener('input', (event) => { state.sensitivity = Number((event.target as HTMLInputElement).value); });
($('#hue') as HTMLInputElement).addEventListener('input', (event) => { state.hue = Number((event.target as HTMLInputElement).value); });
($('#crossfader') as HTMLInputElement).addEventListener('input', (event) => { const value = Number((event.target as HTMLInputElement).value); state.hue = 205 + value * 145; ($('#hue') as HTMLInputElement).value = String(state.hue); document.documentElement.style.setProperty('--mix', String(value)); });
($('#progress') as HTMLInputElement).addEventListener('input', (event) => audio.seek(Number((event.target as HTMLInputElement).value) / 1000));
$('#cueButton').addEventListener('click', () => audio.seek(0));
$('#burstButton').addEventListener('click', () => { if (renderer) { renderer.interaction.frame.burst = 1; renderer.interaction.frame.energy = 1; } document.body.classList.remove('manual-pulse'); requestAnimationFrame(() => document.body.classList.add('manual-pulse')); });
$('#resetButton').addEventListener('click', () => renderer?.reset());
$('#reducedButton').addEventListener('click', () => { state.reducedMotion = !state.reducedMotion; state.notify(); });
const fullscreen = () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen();
$('#fullscreenButton').addEventListener('click', () => void fullscreen());
$('#langButton').addEventListener('click', () => { state.language = state.language === 'en' ? 'zh' : 'en'; applyLanguage(state.language); $('#langButton').textContent = state.language === 'en' ? '中文' : 'EN'; }); applyLanguage(state.language); $('#langButton').textContent = state.language === 'en' ? '中文' : 'EN';

type AppView = 'discover' | 'listen' | 'visual' | 'dj';
const switchView = (view: AppView) => { document.body.dataset.view = view; document.body.classList.toggle('immersed', view === 'visual' || view === 'dj'); player.classList.toggle('visible', view === 'dj'); document.querySelectorAll<HTMLElement>('[data-page]').forEach((page) => page.classList.toggle('active', page.dataset.page === view)); document.querySelectorAll<HTMLButtonElement>('.view-button').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); };
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach((button) => button.addEventListener('click', () => switchView(button.dataset.view as AppView)));
const startDemo = async () => { try { await audio.playDemo(); enter(); switchView('listen'); } catch { showMessage('请检查系统音量，并允许浏览器播放声音'); } };
document.querySelectorAll<HTMLElement>('.demo-card').forEach((card) => card.addEventListener('click', () => void startDemo()));
$('#heroDemoButton').addEventListener('click', () => void startDemo());
$('#dockPlay').addEventListener('click', () => void audio.toggle());
($('#dockProgress') as HTMLInputElement).addEventListener('input', (event) => audio.seek(Number((event.target as HTMLInputElement).value) / 1000));
$('#enterVisualButton').addEventListener('click', () => switchView('visual'));
$('#appLangButton').addEventListener('click', () => { state.language = state.language === 'en' ? 'zh' : 'en'; applyLanguage(state.language); });
document.querySelectorAll<HTMLButtonElement>('.theme-dot').forEach((button) => button.addEventListener('click', () => { document.body.dataset.theme = button.dataset.theme; document.querySelectorAll('.theme-dot').forEach((dot) => dot.classList.toggle('active', dot === button)); }));
($('#lyricsFile') as HTMLInputElement).addEventListener('change', async (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const text = await file.text(); const parsed = [...text.matchAll(/\[(\d{1,2}):(\d{2}(?:\.\d+)?)\]([^\r\n]+)/g)].map((match) => ({ time: Number(match[1]) * 60 + Number(match[2]), lyric: match[3].trim() })).filter((line) => line.lyric).sort((a, b) => a.time - b.time); if (!parsed.length) { showMessage('没有识别到有效的 LRC 时间标签'); return; } const lyrics = $('#lyrics'); lyrics.innerHTML = parsed.map((line) => `<span data-time="${line.time}">${line.lyric.replace(/[<>&]/g, '')}</span>`).join(''); const backdrop = $('#lyricBackdrop'); backdrop.innerHTML = parsed.slice(0, 3).map((line) => `<span>${line.lyric.replace(/[<>&]/g, '')}</span>`).join(''); switchView('listen'); showMessage(`已载入 ${parsed.length} 行歌词`); });

const bindKnob = (inputSelector: string, knobSelector: string, min: number, max: number) => { const input = $(inputSelector) as HTMLInputElement; const knob = $(knobSelector); const paint = () => knob.style.setProperty('--turn', `${-135 + ((Number(input.value) - min) / (max - min)) * 270}deg`); input.addEventListener('input', paint); paint(); };
bindKnob('#filter', '#filterKnob', 0, 1); bindKnob('#sensitivity', '#senseKnob', .5, 2);
const bindHeroKnob = (inputSelector: string, knobSelector: string) => { const input = $(inputSelector) as HTMLInputElement; const knob = $(knobSelector); const minimum = Number(input.min); const maximum = Number(input.max); const step = Number(input.step) || 1; let startY = 0; let startValue = 0; const setValue = (value: number) => { const clamped = Math.max(minimum, Math.min(maximum, value)); input.value = String(Math.round(clamped / step) * step); input.dispatchEvent(new Event('input', { bubbles: true })); }; const paint = () => knob.style.setProperty('--turn', `${-135 + ((Number(input.value) - minimum) / (maximum - minimum)) * 270}deg`); knob.addEventListener('pointerdown', (event) => { event.preventDefault(); input.focus(); knob.setPointerCapture(event.pointerId); startY = event.clientY; startValue = Number(input.value); knob.classList.add('turning'); }); knob.addEventListener('pointermove', (event) => { if (!knob.hasPointerCapture(event.pointerId)) return; setValue(startValue + ((startY - event.clientY) / 160) * (maximum - minimum)); }); const release = (event: PointerEvent) => { if (knob.hasPointerCapture(event.pointerId)) knob.releasePointerCapture(event.pointerId); knob.classList.remove('turning'); }; knob.addEventListener('pointerup', release); knob.addEventListener('pointercancel', release); knob.addEventListener('wheel', (event) => { event.preventDefault(); setValue(Number(input.value) + (event.deltaY < 0 ? step : -step)); }, { passive: false }); input.addEventListener('input', paint); paint(); };
bindHeroKnob('#tempoA', '#tempoKnob'); bindHeroKnob('#volume', '#volumeKnob'); volumeInput.dispatchEvent(new Event('input'));
const bindPlatter = (selector: string, visualOnly = false) => { const platter = $(selector); let lastX = 0; const move = (event: PointerEvent) => { if (!platter.hasPointerCapture(event.pointerId)) return; const delta = event.clientX - lastX; lastX = event.clientX; const angle = Number(platter.dataset.angle ?? 0) + delta * 1.8; platter.dataset.angle = String(angle); platter.style.setProperty('--scratch', `${angle}deg`); if (visualOnly) { state.hue = (state.hue + delta * 1.4 + 360) % 360; ($('#hue') as HTMLInputElement).value = String(state.hue); } else if (audio.duration) audio.seek(Math.max(0, Math.min(1, audio.currentTime / audio.duration + delta / 900))); };
  platter.addEventListener('pointerdown', (event) => { platter.setPointerCapture(event.pointerId); lastX = event.clientX; document.body.classList.add('scratching'); }); platter.addEventListener('pointermove', move); platter.addEventListener('pointerup', () => document.body.classList.remove('scratching')); };
bindPlatter('#platterA'); bindPlatter('#platterB', true);
document.querySelectorAll<HTMLButtonElement>('.performance-pads button').forEach((button, index) => button.addEventListener('click', () => { button.classList.remove('triggered'); requestAnimationFrame(() => button.classList.add('triggered')); if (renderer) { renderer.interaction.frame.burst = 1; renderer.interaction.frame.energy = Math.min(1, .55 + index * .06); } if (button.textContent === 'NEBULA') renderer?.setPreset('nebula'); if (button.textContent === 'GRAVITY') renderer?.setPreset('gravity'); if (button.textContent === 'BLOOM') renderer?.setPreset('bloom'); if (button.textContent === 'RESET') renderer?.reset(); }));
document.querySelectorAll<HTMLButtonElement>('.deck-a .performance-pads button').forEach((button, index) => button.addEventListener('click', () => void audio.triggerDrum(index % 4)));
document.querySelectorAll<HTMLButtonElement>('.deck-b .performance-pads button').forEach((button, index) => button.addEventListener('click', () => { if (index < 4) void audio.triggerHarmony(index); }));
document.querySelectorAll<HTMLInputElement>('.channel input').forEach((input, index) => input.addEventListener('input', () => { if (index === 1) { volumeInput.value = input.value; volumeInput.dispatchEvent(new Event('input')); } }));

type GameMode = 'bpm' | 'rhythm' | 'harmony';
type GameNote = { lane: number; due: number; element: HTMLElement; hit: boolean };
let gameMode: GameMode = 'rhythm', gameRunning = false, gameScore = 0, gameCombo = 0, gameEnds = 0, lastGameBeat = 0, nextPredictedBeat = 0, rhythmStep = 0, harmonyStep = 0, lastBpmScore = 0; const gameNotes: GameNote[] = [];
const gameCopy = { bpm: 'Turn the tempo engine into the target zone: 128 BPM', rhythm: 'Hit A · S · D · F with the live beat', harmony: 'Follow the chord progression: C · Am · F · G' };
const clearGameNotes = () => gameNotes.splice(0).forEach((note) => note.element.remove());
const setGameMode = (mode: GameMode) => { gameMode = mode; gameRunning = false; clearGameNotes(); document.body.classList.remove('challenge-active'); document.querySelectorAll<HTMLButtonElement>('[data-game-mode]').forEach((button) => button.classList.toggle('active', button.dataset.gameMode === mode)); $('#gameObjective').textContent = gameCopy[mode]; document.querySelector('.harmony-keys')?.classList.toggle('visible', mode === 'harmony'); $('#gameCallout').textContent = mode === 'bpm' ? 'FIND 128 BPM' : 'PRESS START TO DROP IN'; };
document.querySelectorAll<HTMLButtonElement>('[data-game-mode]').forEach((button) => button.addEventListener('click', () => setGameMode(button.dataset.gameMode as GameMode)));
const showJudge = (label: string, quality: 'perfect' | 'good' | 'miss') => { const callout = $('#gameCallout'); callout.textContent = label; callout.dataset.quality = quality; document.body.classList.remove('game-hit'); requestAnimationFrame(() => document.body.classList.add('game-hit')); };
const updateScore = (points: number, quality: 'perfect' | 'good' | 'miss') => { if (points > 0) { gameCombo++; gameScore += points + gameCombo * 5; } else gameCombo = 0; if (quality === 'perfect') { void audio.triggerPerfect(); document.body.classList.remove('perfect-hit'); requestAnimationFrame(() => { document.body.classList.add('perfect-hit'); window.setTimeout(() => document.body.classList.remove('perfect-hit'), 320); }); } $('#gameScore').textContent = String(gameScore).padStart(6, '0'); $('#gameCombo').textContent = `×${gameCombo}`; showJudge(quality.toUpperCase(), quality); };
const hitLane = (lane: number) => { if (!gameRunning || gameMode === 'bpm') return; const laneElement = document.querySelector<HTMLElement>(`.note-highway .lane[data-lane="${lane}"]`); laneElement?.classList.remove('pressed'); requestAnimationFrame(() => laneElement?.classList.add('pressed')); window.setTimeout(() => laneElement?.classList.remove('pressed'), 120); if (gameMode === 'rhythm') void audio.triggerDrum(lane); else void audio.triggerHarmony(lane); const now = performance.now(); const note = gameNotes.filter((item) => !item.hit && item.lane === lane).sort((a,b) => Math.abs(a.due-now)-Math.abs(b.due-now))[0]; if (!note) { updateScore(0, 'miss'); return; } const error = Math.abs(note.due - now); if (error < 115) { note.hit = true; note.element.classList.add('hit'); updateScore(100, 'perfect'); } else if (error < 230) { note.hit = true; note.element.classList.add('hit'); updateScore(55, 'good'); } else updateScore(0, 'miss'); };
const chooseLane = (frame: AudioFrame) => { if (gameMode === 'harmony') return harmonyStep++ % 4; const step = rhythmStep++; if (frame.bass >= frame.mid && frame.bass >= frame.treble) return [0, 2, 0, 1][step % 4]; if (frame.treble > frame.mid) return [3, 1, 3, 2][step % 4]; return [1, 2, 1, 3][step % 4]; };
const spawnGameNote = (now: number, frame: AudioFrame) => { const lane = chooseLane(frame); const element = document.createElement('i'); element.className = 'game-note'; element.dataset.lane = String(lane); const laneElement = document.querySelectorAll<HTMLElement>('.note-highway .lane')[lane]; if (!laneElement) return; const beatDuration = 60000 / audio.targetBpm; const travel = Math.max(1250, Math.min(2600, beatDuration * 4)); laneElement.append(element); gameNotes.push({ lane, due: now + travel, element, hit: false }); element.style.setProperty('--travel', `${travel}ms`); };
const gameOnAudioFrame = (frame: AudioFrame, now: number) => { if (!gameRunning || gameMode === 'bpm') return; const beatDuration = 60000 / audio.targetBpm; const minimumGap = Math.max(240, beatDuration * .5); const detectedBeat = frame.transient > .24 && now - lastGameBeat >= minimumGap; if (detectedBeat) { lastGameBeat = now; nextPredictedBeat = now + beatDuration; spawnGameNote(now, frame); } else if (now >= nextPredictedBeat && now - lastGameBeat >= minimumGap) { lastGameBeat = now; nextPredictedBeat = now + beatDuration; spawnGameNote(now, frame); } };
const gameLoop = (now: number) => { if (gameRunning) { for (let index = gameNotes.length - 1; index >= 0; index--) { const note = gameNotes[index]; if (!note.hit && now > note.due + 240) { note.hit = true; note.element.classList.add('missed'); updateScore(0, 'miss'); } if (now > note.due + 900) { note.element.remove(); gameNotes.splice(index, 1); } } if (now >= gameEnds) { gameRunning = false; document.body.classList.remove('challenge-active'); showJudge(`SET COMPLETE · ${gameScore}`, 'perfect'); } } requestAnimationFrame(gameLoop); }; requestAnimationFrame(gameLoop);
$('#startChallenge').addEventListener('click', async () => { if (!audio.playing) await audio.playDemo(); clearGameNotes(); gameScore = 0; gameCombo = 0; gameRunning = true; lastGameBeat = 0; nextPredictedBeat = performance.now() + 420; rhythmStep = 0; harmonyStep = 0; lastBpmScore = 0; document.body.classList.add('challenge-active'); gameEnds = performance.now() + 30000; $('#gameScore').textContent = '000000'; $('#gameCombo').textContent = '×0'; showJudge(gameMode === 'bpm' ? 'TARGET · 128 BPM' : 'READY · FEEL THE BEAT', 'good'); });
const tempoInput = $('#tempoA') as HTMLInputElement; tempoInput.addEventListener('input', () => { const bpm = Number(tempoInput.value); audio.setBpm(bpm); $('#tempoValue').textContent = String(bpm); $('#bpmReadout').textContent = String(bpm); if (gameRunning && gameMode === 'bpm') { const error = Math.abs(128 - bpm); const now = performance.now(); if (error <= 1 && now - lastBpmScore > 700) { lastBpmScore = now; updateScore(120, 'perfect'); } else if (error <= 4 && now - lastBpmScore > 700) { lastBpmScore = now; updateScore(40, 'good'); } else if (error > 4) $('#gameCallout').textContent = bpm < 128 ? 'PUSH FASTER →' : '← PULL BACK'; } }); tempoInput.dispatchEvent(new Event('input'));
document.querySelectorAll<HTMLButtonElement>('.note-highway .lane').forEach((lane) => lane.addEventListener('click', () => hitLane(Number(lane.dataset.lane))));
document.querySelectorAll<HTMLButtonElement>('[data-chord]').forEach((button) => button.addEventListener('click', () => hitLane(Number(button.dataset.chord))));
addEventListener('keydown', (event) => { const lane = ['a','s','d','f'].indexOf(event.key.toLowerCase()); if (lane >= 0 && document.body.dataset.view === 'dj') hitLane(lane); });

let dragging = 0; const dropZone = $('#dropZone');
addEventListener('dragenter', (event) => { event.preventDefault(); dragging++; dropZone.classList.add('visible'); });
addEventListener('dragover', (event) => event.preventDefault());
addEventListener('dragleave', () => { if (--dragging <= 0) { dragging = 0; dropZone.classList.remove('visible'); } });
addEventListener('drop', (event) => { event.preventDefault(); dragging = 0; dropZone.classList.remove('visible'); void load(event.dataTransfer?.files[0]); });
addEventListener('keydown', (event) => { if ((event.target as HTMLElement).matches('input,button')) return; if (event.code === 'Space') { event.preventDefault(); void audio.toggle(); } if (event.key.toLowerCase() === 'f') void fullscreen(); if (event.key.toLowerCase() === 'h') { state.uiHidden = !state.uiHidden; state.notify(); } if (/^[1-3]$/.test(event.key)) renderer?.setPreset(registry.list()[Number(event.key) - 1].id); });
document.addEventListener('visibilitychange', () => { if (document.hidden && audio.playing) showMessage('Visuals paused while this tab is hidden'); });

window.setInterval(() => { const duration = audio.duration || 32; const progressValue = String(audio.currentTime / duration * 1000); ($('#dockProgress') as HTMLInputElement).value = progressValue; $('#dockTime').textContent = `${format(audio.currentTime)} / ${format(duration)}`; const dockName = $('#dockTrackName'); if (dockName.firstChild) dockName.firstChild.textContent = audio.name === 'NO SIGNAL' ? 'Orbital Signal' : audio.name; $('#dockPlay').textContent = audio.playing ? 'Ⅱ' : '▶'; const lines = [...document.querySelectorAll<HTMLElement>('#lyrics [data-time]')]; let active = lines[0]; lines.forEach((line) => { if (audio.currentTime >= Number(line.dataset.time)) active = line; }); lines.forEach((line) => line.classList.toggle('active', line === active)); if (active) $('#lyricTitle').textContent = active.textContent ?? ''; }, 120);
let statTick = 0; let lastBeat = 0;
const frame = (delta: number) => { const result = audio.frame(delta); const now = performance.now(); fallback?.render(result, state.hue); gameOnAudioFrame(result, now); const duration = audio.duration; ($('#progress') as HTMLInputElement).value = duration ? String(audio.currentTime / duration * 1000) : '0'; $('#timeLabel').textContent = `${format(audio.currentTime)} / ${format(duration)}`; document.documentElement.style.setProperty('--level', result.rms.toFixed(3)); document.documentElement.style.setProperty('--bass', result.bass.toFixed(3)); if (result.transient > .55 && now - lastBeat > 260) { lastBeat = now; document.body.classList.remove('beat'); requestAnimationFrame(() => document.body.classList.add('beat')); } if (++statTick % 12 === 0) { $('#freqReadout').textContent = String(result.treble * 999).padStart(5, '0'); $('#energyReadout').textContent = result.rms.toFixed(2); $('#sourceBpm').textContent = `SOURCE · ${audio.detectedBpm} BPM · ${audio.playbackRate.toFixed(2)}×`; const activeBars = Math.round(result.rms * 15); document.querySelectorAll<HTMLElement>('.vu i').forEach((bar, index) => bar.classList.toggle('active', index < activeBars)); } return result; };
if (renderer) renderer.onFrame = frame; else { let last = performance.now(); const loop = (now: number) => { frame(Math.min(.05, (now - last) / 1000)); last = now; requestAnimationFrame(loop); }; requestAnimationFrame(loop); }
let idleTimer = 0; const wake = () => { document.body.classList.remove('idle'); clearTimeout(idleTimer); if (document.body.classList.contains('immersed')) idleTimer = window.setTimeout(() => document.body.classList.add('idle'), 3800); }; ['pointermove', 'pointerdown', 'keydown'].forEach((name) => addEventListener(name, wake));
addEventListener('beforeunload', () => { audio.dispose(); renderer?.dispose(); });
